# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               PlataCode
tagline:             The Jekyll Butler
url:                 http://platacode.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              John Aldrin Plata
  url:               https://twitter.com/silverxjohn31
  email:             johnaldrinplata@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole
